### ISSUE TITLE
1.9.4 glitch with users

### ISSUE THREAD

**Issue by smack17** [Dandielo/dtlTraders#56]
When I open shop, things work fine, but when others attempt to do this, the console is spammed with stuff like

14.05 21:45:49 [Server] INFO [21:45:49 INFO]: WOOD
14.05 21:45:49 [Server] INFO [21:45:49 INFO]: WOOD
14.05 21:45:49 [Server] INFO [21:45:49 INFO]: magic_wand
14.05 21:45:49 [Server] INFO [21:45:49 INFO]: WOOD
14.05 21:45:49 [Server] INFO [21:45:49 INFO]: d
14.05 21:45:49 [Server] INFO [21:45:49 INFO]: .hidef

Note that this is just a small portion of what is spammed. For the more part it spams WOOD, magic_wand (from the magic plugin I have, which strangely uses their own type of shop, not dtlTraders), d, and .hidef. What I find strange is that this only happens for users, and not any staff that I've given dtl.trader.* (or whatever the node is to give them permissions for the whole plugin) which makes me believe its something permissions based, but I've tried giving users a lot of different permissions and nothing seems to help.

I am running on version 3.4.3 of this plugin on the latest version of spigot.

Heres a screenshot of the console:

![error](https://cloud.githubusercontent.com/assets/13319514/15737176/aca29138-2872-11e6-80ff-90e99e75c8ce.png)

**Comment by Dandielo** [comment]
Sorry for not responding for your issue, I wont really be any helpful with Bukkit plugin related issue because I dont develop them anymore, I do not find it interesting and/or entraining thus all mu Bukkit projects are abandoned. 

Maybe some1 can take this plugin and make it awesome again, but this wont be me, sorry :(

P.S. This isn't probably any big issue, I just dont got the time to setup even that workspace again sorry :/
