### ISSUE TITLE
draining rf

### ISSUE THREAD

**Issue by dragonaslin** [Dandielo/dtlTraders#58]
Hello i have your version 3.2.3 book fix for bucket 1.7.9. When i make an npc trader and click on it it drains all rf from anything in inventory, especially draconic evolution. Is there a fix for this?

**Comment by Dandielo** [comment]
Sorry for not responding for your issue, I wont really be any helpful with Bukkit plugin related issue because I dont develop them anymore, I do not find it interesting and/or entraining thus all mu Bukkit projects are abandoned. 

Maybe some1 can take this plugin and make it awesome again, but this wont be me, sorry :(

P.S. For example i don't know what this RF is lol
